apiVersion: v1
kind: Service
metadata:
 name: train-schedule-service
spec:
 type: NodePort
 selector:
  app: train-schedule
 ports:
  - port: 8080
    nodePort: 8080
    protocol: TCP
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: train-schedule-deployment
 lables:
  app: train-schedule
spec:
 replicas: 2
 selectors:
  matchLabels:
   app: train-schedule
 template:
  metadata:
   lables:
    app: train-schedule
  spec:
   containers: 
    - name: train-schedule
      image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
      ports:
       - containerPort: 8080
 
